name: Update NoirBird-WR-Patcher to the latest version of the code

on:
  push:
    paths:
      - "NoirBird-WR-Patcher.py"  # Run this workflow on every push to NoirBird-WR-Patcher.py
  pull_request:
    paths:
      - "NoirBird-WR-Patcher.py"  # Run this workflow on every pull request to NoirBird-WR-Patcher.py

jobs:
  build_and_release:
    runs-on: windows-2019  # Use Windows 10 runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Use Python 3.11

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Compile using PyInstaller
        run: |
          pyinstaller -F --uac-admin NoirBird-WR-Patcher.py

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Release  # Specify the tag name for the release
          release_name: Exe File  # Specify the release name
          draft: false  # Publish the release immediately
          prerelease: false  # This is a stable release

      - name: Upload to Release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/NoirBird-WR-Patcher.exe  # Path to the compiled executable
          asset_name: NoirBird-WR-Patcher.exe  # Name of the asset as it will appear in the release
          asset_content_type: application/octet-stream
